spring:
  datasource:
    username: root
    password: js@201211
    url: jdbc:mysql://192.168.197.12:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.197.12:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 11000
logging:
  level:
    com.atguigu.gulimall:debug